function verify_gradient_stop_no_extra_evaluations()
%VERIFY_GRADIENT_STOP_NO_EXTRA_EVALUATIONS checks gradient-stop accounting.

tests_dir = fileparts(mfilename('fullpath'));
root_dir = fileparts(tests_dir);
old_path = path();
cleanup = onCleanup(@() path(old_path));
addpath(fullfile(root_dir, 'src'));
x0 = [1.1; 0.9; 1.2];
options = final_gradient_options(numel(x0));
defaults_options = rmfield(options, { ...
    'use_gradient_reference_consistency', ...
    'grad_reference_finite_difference_error_tol'});

[explicit, explicit_calls] = run_with_counter(options);
[defaults, default_calls] = run_with_counter(defaults_options);

assert(strcmp(explicit.output.message, 'The estimated gradient is small.'), ...
    'The focused case did not activate the estimated-gradient stop.');
assert(isequaln(explicit.x, defaults.x) ...
    && isequaln(explicit.f, defaults.f) ...
    && explicit.exitflag == defaults.exitflag ...
    && isequaln(explicit.output.fhist, defaults.output.fhist) ...
    && isequaln(explicit_calls, default_calls), ...
    'The tuned gradient-stop defaults differ from the explicit final options.');
assert_objective_accounting(explicit, explicit_calls);
assert_objective_accounting(defaults, default_calls);

fprintf('GRADIENT_STOP_NO_EXTRA_EVALUATIONS_OK\n');

    function [result, calls] = run_with_counter(run_options)
        calls = zeros(numel(x0), 0);
        [result.x, result.f, result.exitflag, result.output] = ...
            bds(@counted_objective, x0, run_options);

        function value = counted_objective(x)
            calls(:, end + 1) = x(:);
            value = sum((x(:) - 1).^2);
        end
    end

end

function options = final_gradient_options(n)

options = struct('Algorithm', 'cbds', ...
    'MaxFunctionEvaluations', 500 * n, 'StepTolerance', 1e-6, ...
    'alpha_init', ones(n, 1), 'seed', 0, ...
    'use_productive_direction_memory', true, ...
    'use_iteration_pattern_step', true, ...
    'use_momentum_extrapolation', true, ...
    'use_function_value_stop', false, ...
    'use_estimated_gradient_stop', true, ...
    'grad_window_size', 1, 'grad_tol', 1e-2, ...
    'lipschitz_constant', 1e3, ...
    'use_gradient_reference_consistency', true, ...
    'grad_reference_finite_difference_error_tol', 1/30, ...
    'output_xhist', true);

end

function assert_objective_accounting(result, calls)

assert(result.output.funcCount == size(calls, 2), ...
    'output.funcCount does not match the actual objective-call count.');
assert(isequaln(result.output.xhist, calls), ...
    'Some objective calls are missing from the ordinary evaluation history.');
assert(numel(result.output.fhist) == size(calls, 2), ...
    'Function-value history and actual objective-call count differ.');

end
