function manifest = run_gradient_stop_final_comparison()
%RUN_GRADIENT_STOP_FINAL_COMPARISON compares the three final stop choices.

stopping_dir = fileparts(mfilename('fullpath'));
auto_alpha_dir = fileparts(stopping_dir);
research_dir = fileparts(auto_alpha_dir);
repo_dir = fileparts(research_dir);
tests_dir = fullfile(repo_dir, 'tests');
cd(repo_dir);
setup;
addpath(tests_dir);
addpath(fullfile(tests_dir, 'competitors'));
optiprofiler_root = fullfile(getenv('HOME'), 'local', 'optiprofiler', ...
    'matlab', 'optiprofiler');
addpath(fullfile(optiprofiler_root, 'src'));
addpath(fullfile(optiprofiler_root, 'problem_libs'));
addpath(fullfile(optiprofiler_root, 'problem_libs', 's2mpj'));

problem_names = frozen_problem_names();
solver_names = { ...
    'auto-accelerated-all-on-500n-no-optional-stop', ...
    'auto-accelerated-all-on-500n-function-stop-fw20-ft1em6-gw1-gt1em6', ...
    ['auto-accelerated-all-on-500n-gradient-stop-', ...
    'fw20-ft1em6-gw1-gt1em6-grc0p1-grs10000'], ...
    ['auto-accelerated-all-on-500n-stop-', ...
    'fw20-ft1em6-gw1-gt1em6-grc0p1-grs10000']};
timestamp = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
run_root = fullfile(stopping_dir, 'testdata', ...
    ['gradient_stop_final_comparison_', timestamp]);
mkdir(run_root);

manifest = struct('status', 'RUNNING', ...
    'started_at', char(datetime('now')), 'run_root', run_root, ...
    'problem_names', {problem_names}, ...
    'features', {{'plain', 'linearly_transformed'}}, ...
    'solver_names', {solver_names}, ...
    'strategy_labels', {{'no-stop', 'function-only', ...
    'pure-gradient', 'combined-OR'}}, ...
    'func_window_size', 20, 'func_tol', 1e-6, ...
    'grad_window_size', 1, 'grad_tol', 1e-6, ...
    'reference_consistency_tolerance', 0.1, ...
    'reference_relative_tolerance', 1e-2, ...
    'max_eval_factor', 500, 'n_runs', 1, ...
    'uses_extra_function_evaluations', false);
save(fullfile(run_root, 'manifest.mat'), 'manifest');

for i_feature = 1:numel(manifest.features)
    feature_name = manifest.features{i_feature};
    options = benchmark_options(problem_names, solver_names, feature_name, ...
        run_root);
    fprintf('GRADIENT_STOP_FINAL_COMPARISON_FEATURE_START=%s\n', feature_name);
    [solver_scores, profile_scores, curves] = profile_optiprofiler(options);
    output_solved_fractions = extract_output_solved_fractions(curves, ...
        numel(solver_names), 5);
    [raw, source_data] = extract_raw_results( ...
        options.savepath, options.benchmark_id, solver_names);
    evaluation_totals = sum(raw.evaluation_counts, 1)';
    evaluation_savings = evaluation_totals(1) - evaluation_totals;
    activation_counts = sum(raw.evaluation_counts < ...
        raw.evaluation_counts(:, 1), 1)';
    save(fullfile(run_root, [feature_name, '_scores.mat']), ...
        'solver_scores', 'profile_scores', 'curves', ...
        'output_solved_fractions', 'raw', 'evaluation_totals', ...
        'evaluation_savings', 'activation_counts', 'source_data');
    copy_native_summary(options, run_root, feature_name);
    fprintf('GRADIENT_STOP_FINAL_%s_MIN_SOLVED=%s\n', upper(feature_name), ...
        join_numeric_row(min(output_solved_fractions, [], 2)'));
    fprintf('GRADIENT_STOP_FINAL_%s_EVALUATION_TOTALS=%s\n', ...
        upper(feature_name), join_numeric_row(evaluation_totals'));
    fprintf('GRADIENT_STOP_FINAL_%s_ACTIVATION_COUNTS=%s\n', ...
        upper(feature_name), join_numeric_row(activation_counts'));
    fprintf('GRADIENT_STOP_FINAL_COMPARISON_FEATURE_OK=%s\n', feature_name);
end

manifest.status = 'COMPLETE';
manifest.finished_at = char(datetime('now'));
save(fullfile(run_root, 'manifest.mat'), 'manifest');
fprintf('GRADIENT_STOP_FINAL_COMPARISON_RUN_ROOT=%s\n', run_root);
fprintf('GRADIENT_STOP_FINAL_COMPARISON_OK\n');

end

function options = benchmark_options(problem_names, solver_names, ...
        feature_name, run_root)

options = struct('problem_names', {problem_names}, ...
    'mindim', 6, 'maxdim', 50, 'plibs', 's2mpj', ...
    'feature_name', feature_name, 'feature_display_name', feature_name, ...
    'n_runs', 1, 'seed', 0, 'max_eval_factor', 500, ...
    'max_tol_order', 5, 'n_jobs', 40, 'draw_hist_plots', 'none', ...
    'solver_verbose', 0, 'solver_names', {solver_names}, ...
    'benchmark_id', ['gradient_stop_final_comparison_', feature_name], ...
    'savepath', fullfile(run_root, feature_name));
mkdir(options.savepath);

end

function solved_fractions = extract_output_solved_fractions(curves, ...
        n_solvers, n_tolerances)

solved_fractions = nan(n_solvers, n_tolerances);
for i_tol = 1:n_tolerances
    for i_solver = 1:n_solvers
        curve = curves{i_tol}.out.perf{i_solver, end};
        solved_fractions(i_solver, i_tol) = curve(2, end);
    end
end

end

function [raw, source_data] = extract_raw_results( ...
        savepath, benchmark_id, solver_names)

listing = dir(fullfile(savepath, [benchmark_id, '*'], '**', ...
    'data_for_loading.mat'));
assert(isscalar(listing), 'Expected one data_for_loading.mat file.');
source_data = fullfile(listing(1).folder, listing(1).name);
loaded = load(source_data, 'results_plibs');
results = loaded.results_plibs{1};
assert(isequal(results.solver_names(:), solver_names(:)), ...
    'Unexpected solver order.');
raw = struct('problem_names', {results.problem_names(:)}, ...
    'evaluation_counts', reshape(results.n_evals, [], numel(solver_names)), ...
    'merit_outputs', reshape(results.merit_outs, [], numel(solver_names)));

end

function copy_native_summary(options, run_root, feature_name)

listing = dir(fullfile(options.savepath, [options.benchmark_id, '*'], ...
    '**', 'summary_*.pdf'));
assert(~isempty(listing), 'OptiProfiler did not create a native summary PDF.');
[~, index] = max([listing.datenum]);
copyfile(fullfile(listing(index).folder, listing(index).name), ...
    fullfile(run_root, [feature_name, '_final_comparison_optiprofiler.pdf']));

end

function text = join_numeric_row(values)
parts = arrayfun(@(value) sprintf('%.16g', value), values, ...
    'UniformOutput', false);
text = strjoin(parts, ',');
end

function names = frozen_problem_names()

selection = struct('ptype', 'u', 'mindim', 6, 'maxdim', 50, ...
    'excludelist', {{ ...
    'DIAMON2DLS', 'DIAMON2D', 'DIAMON3DLS', 'DIAMON3D', ...
    'DMN15102LS', 'DMN15102', 'DMN15103LS', 'DMN15103', ...
    'DMN15332LS', 'DMN15332', 'DMN15333LS', 'DMN15333', ...
    'DMN37142LS', 'DMN37142', 'DMN37143LS', 'DMN37143', ...
    'ROSSIMP3_mp', 'BAmL1SPLS', 'FBRAIN3LS', 'GAUSS1LS', ...
    'GAUSS2LS', 'GAUSS3LS', 'HYDC20LS', 'HYDCAR6LS', ...
    'LUKSAN11LS', 'LUKSAN12LS', 'LUKSAN13LS', 'LUKSAN14LS', ...
    'LUKSAN17LS', 'LUKSAN21LS', 'LUKSAN22LS', 'METHANB8LS', ...
    'METHANL8LS', 'SPINLS', 'VESUVIALS', 'VESUVIOLS', ...
    'VESUVIOULS', 'YATP1CLS'}});
names = s2mpj_select(selection);
assert(numel(names) == 122, 'Expected the frozen 122-problem set.');

end
